language: node_js
node_js:
  - "stable"

notifications:
  email: false

env:
  global:
    - secure: "B2UKRGRY7DzX5oaWY6uStho3mZCLRi5upENonTI8SlgZJSNyCgsY7KJ65/Nl0x7INewDsiLR7fpwBB+FVNeTJxPoNrefOzgHCcDGSsV1fQtZv93aGrt+YWUqGK+qU6e1xqt0kovweHhziar5d6jltal0KZzTQdzs21sJDVYRooQaXada/qrfLVlB511RjuZDuz2+JqkBrGZvTp/iZJLh4dTsCDfni2IjK5C0cVZ7FJYXSmwIursqwTWAtrmyGBQ7q8robPrGQP1vgteuMcFeduLPfrk15NMrpB2eBtWA0hDOL3FoHNpWw7yCUo2fvv/blawwDan8Pvlf21GpJtVX/oyD8jFSxsLmbQfBK9g5MmFPDIfkr4A6i4MC0ETpVUs9kAPjeF2Wh8t2hJirMnesKeWVKK9W0Dnu/zkrvCbcKsV6dS0oYVKo1FVSj1o1r9k/G/NgVkWdyh2IwcZ3/OVt8DXHUKbTlS5nFoPMWyi95PGuN96z3V/r/yX5GFSXs9oaC8hGSB2kBg9895VJXdOU/+BIFHH/gn+Xa+/xxvZSEq6aKU9Mhkc5rAqg6/ceobHcTrOuh1hkU0+QFu6JWcAMcZ1YczxG5LE6/1fxsms/SlqNmbkCL5KwyJw79lk7y2bNc9cJFaUuUD2oo1Q3SvYVvdblz9qnSCpc9AWfl87HtKc="

before_script:
  - yarn install

script:
  - yarn test
  - yarn flow

after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GITHUB_TOKEN:@github.com" > .git/credentials

deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: development

cache: yarn
