name: Build
on:
  push:
    branches:
      - '*/*'
  pull_request:
jobs:
  publish:
    name: Build UI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.4.0
        with:
          cache: 'npm'
          node-version: '16'
      - run: npm ci
      - run: npm run build
