name: Publish
on:
  push:
    branches:
      - development
jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-24.04
    environment: build
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - uses: actions/setup-node@v7
        with:
          cache: 'pnpm'
          node-version: 24
      - run: pnpm install
      - run: pnpm run build
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -u "GitHub Actions Bot <actions@github.com>" -b master -d build --cname timon-borter.ch
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
