name: Publish
on:
  push:
    branches:
      - development
jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-20.04
    environment: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.3.0
        with:
          cache: 'npm'
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -u "GitHub Actions Bot <actions@github.com>" -b master -d build --cname timon-borter.ch
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
